name: "CI"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # run additionally every week to catch
  # breakage due to package updates
  schedule:
    - cron: '23 23 * * 0'

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v8
      with:
        name: spacecookie
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: nix-build
      run: nix-build
